services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: CDM_RABBIT_MQ
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env.docker.rabbitmq
    networks:
      - cdm-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Databases
  user-database:
    image: postgres:15
    container_name: cdm-user-database
    env_file:
      - .env.docker.user
    ports:
      - "5009:5432"
    volumes:
      - cdm-user-database:/var/lib/postgresql/data
    networks:
      - cdm-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  cdm-wallet-db:
    image: postgres:15
    env_file:
      - .env.docker
    ports:
      - "5006:5432"
    volumes:
      - cdm-wallet-db:/var/lib/postgresql/data
    networks:
      - cdm-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_wallet" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Services
  gateway-service:
    build: ./modules/gateway
    container_name: cdm-gateway-service
    env_file:
      - .env.docker.gateway
    ports:
      - "4000:4000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - cdm-network

  auth-service:
    build: ./modules/authentification
    container_name: cdm-auth-service
    env_file:
      - .env.docker.auth
    ports:
      - "4001:4001"
    depends_on:
      user-database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - cdm-network

  user-service:
    build: ./modules/user
    container_name: cdm-user-service
    env_file:
      - .env.docker.user
    ports:
      - "4009:4009"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - cdm-network

  cdm-wallet-service:
    build: .
    env_file:
      - .env.docker
    ports:
      - "4006:4006"
    depends_on:
      cdm-wallet-db:
        condition: service_healthy
      cdm-rabbitmq:
        condition: service_healthy
    networks:
      - cdm-network

volumes:
  cdm-user-database:
  cdm-wallet-db:


networks:
  cdm-network:
    driver: bridge